##### 1. Python program to add two Matrices

In [3]:
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of First Matrix:")
matrix_1= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_1:
    print(n)

print("Enter the elements of Second Matrix:")
matrix_2= [[int(input()) for i in range(column)] for i in range(rows)]
for n in matrix_2:
    print(n)
    
result=[[0 for i in range(column)] for i in range(rows)]

for i in range(rows):
    for j in range(column):
        result[i][j] = matrix_1[i][j]+matrix_2[i][j]

print("The Sum of Above two Matrices is : ")
for r in result:
    print(r)

Enter the Number of rows : 3
Enter the Number of Columns: 3
Enter the elements of First Matrix:
1
2
3
4
5
6
7
8
9
First Matrix is: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Enter the elements of Second Matrix:
1
1
2
2
3
3
4
4
5
[1, 1, 2]
[2, 3, 3]
[4, 4, 5]
The Sum of Above two Matrices is : 
[2, 3, 5]
[6, 8, 9]
[11, 12, 14]


##### 2.	Python program to multiply two matrices

In [5]:
rows = int(input("Enter the Number of rows  for the first matrix: " ))
column = int(input("Enter the Number of Columns for the first matrix: "))

print("Enter the elements of First Matrix:")
matrix_1= [[int(input()) for i in range(column)] for i in range(rows)]

print("First Matrix is: ")
for n in matrix_1:
    print(n)
#the number of columns of first matrix is equal to the number of rows of second matrix
column_1 = int(input("Enter the Number of Columns for the second matrix: "))

print("Enter the elements of Second Matrix:")

matrix_2= [[int(input()) for i in range(column_1)] for i in range(column)]
for n in matrix_2:
    print(n)
    
result=[[0 for i in range(column_1)] for i in range(rows)]

for i in range(len(matrix_1)):
    for j in range(len(matrix_2[0])):
        for k in range(len(matrix_2)):
            result [i][j]+=matrix_1[i][k]*matrix_2[k][j]
print("\nMatrix_1 X Matrix_2 is: ")
for r in result:
    print(r)

Enter the Number of rows  for the first matrix: 2
Enter the Number of Columns for the first matrix: 2
Enter the elements of First Matrix:
1
2
3
4
First Matrix is: 
[1, 2]
[3, 4]
Enter the Number of Columns for the second matrix: 1
Enter the elements of Second Matrix:
2
3
[2]
[3]

Matrix_1 X Matrix_2 is: 
[8]
[18]


#### 3.	Python program for Matrix Product

In [6]:
# 3x2 matrix
X = [ [1,2],[3,4],[4,5] ]
# 2x3 matrix
Y = [ [1,2,3],[4,5,6] ]

# resultant matrix
result = [ [0,0,0],[0,0,0],[0,0,0] ]

my_list = []
# iterating rows of X matrix
for i in range( len(X) ):
   # iterating columns of Y matrix
   for j in range(len(Y[0])):
       # iterating rows of Y matrix
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
  

for r in result:
   print(r)

[9, 12, 15]
[19, 26, 33]
[24, 33, 42]


##### 4.	Adding and Subtracting Matrices in Python

In [8]:
import numpy as np
data1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
sum_matrices = data1 + data1
print("Addition of matrices: ", sum_matrices)

Addition of matrices:  [[ 2  4  6  8]
 [10 12 14 16]]


In [11]:
subtraction_matrices = data1 + data1
print("Subtraction of matrices: ", subtraction_matrices)

Subtraction of matrices:  [[ 2  4  6  8]
 [10 12 14 16]]


##### 5.	Transpose a matrix in Single line in Python

In [13]:
print(data1)
print("\n")
print(np.transpose(data1))

[[1 2 3 4]
 [5 6 7 8]]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


##### 6.	Python | Matrix creation of n*n

In [16]:
# initializing N
N = 3
  
# printing dimension
print("The dimension : " + str(N))
  
# using list comprehension
# matrix creation of n * n
res = [list(range(1 + N * i, 1 + N * (i + 1)))
                            for i in range(N)]
  
# print result
print("The created matrix of N * N: " + str(res))

The dimension : 3
The created matrix of N * N: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


##### 7.	Python | Get Kth Column of Matrix

In [20]:
lists = [[1, 2, 3], [2, 4, 5], [6, 7, 8]]
  
# printing original list
print("The original list is : " + str(lists))
  
# initialize K
K = 1
  
# Get Kth Column of Matrix
# using list comprehension
res = [i[K] for i in lists]
  
# printing result
print("The Kth column of matrix is : " + str(res))

The original list is : [[1, 2, 3], [2, 4, 5], [6, 7, 8]]
The Kth column of matrix is : [2, 4, 7]


##### 8.	Python – Vertical Concatenation in Matrix

In [1]:
import numpy as np

an_array = np.array([1, 2])
another_array = np.array([3, 4])
stacked_array = np.vstack((an_array, another_array))
print(stacked_array)

[[1 2]
 [3 4]]


##### 9.	Python program to check if a string is palindrome or not

In [13]:
string = input("Enter a string: ")

if (string == string[::-1]):
    print ("String is palindrome")
else:
    print ("String is not a palindrome")
        


Enter a string: madam
String is palindrome


##### 10.	Python program to check whether the string is Symmetrical or Palindrome

In [19]:
def check_palindrome(my_str):
    mid_val = (len(my_str)-1)//2
    start = 0
    end = len(my_str)-1
    flag = 0
    while(start<mid_val):
        if (my_str[start]== my_str[end]):
            start += 1
            end -= 1
        else:
            flag = 1
            break;
        if flag == 0:
            print("The entered string is palindrome")
        else:
            print("The entered string is not palindrome")
def check_symmetry(my_str):
    n = len(my_str)
    flag = 0
    if n%2:
        mid_val = n//2 +1
    else:
        mid_val = n//2
    start_1 = 0
    start_2 = mid_val
    while(start_1 < mid_val and start_2 < n):
        if (my_str[start_1]== my_str[start_2]):
            start_1 = start_1 + 1
            start_2 = start_2 + 1
        else:
            flag = 1
            break
    if flag == 0:
        print("The entered string is symmetrical")
    else:
        print("The entered string is not symmetrical")
my_string = 'yoyo'
my_string1 = 'madam'
print("The method to check a palindrome is being called...")
check_palindrome(my_string)
check_palindrome(my_string1)
print("The method to check symmetry is being called...")
check_symmetry(my_string)
check_symmetry(my_string1)

The method to check a palindrome is being called...
The entered string is palindrome
The entered string is palindrome
The method to check symmetry is being called...
The entered string is symmetrical
The entered string is not symmetrical
